export const SET_MOVIES = 'SET_MOVIES';
export const ADD_MOVIE = 'ADD_MOVIE';
export const EDIT_MOVIE = 'EDIT_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';

export const SET_CATEGORIES = 'SET_CATEGORIES';

export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADING_FINISH = 'USER_LOADING_FINISH';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';

export const POLLS_LOADING_START = 'POLLS_LOADING_START';
export const POLLS_LOADING_FINISH = 'POLLS_LOADING_FINISH';
export const SET_POLLS = 'SET_POLLS';
export const UPDATE_CURRENT_VOTES = 'UPDATE_CURRENT_VOTES';
export const VOTE_ON_POLL = 'VOTE_ON_POLL';
